"""Pick 20 random words from the magnet-poetry pool and update INITIAL_WORDS in public/index.html.

Word pool sourced from https://github.com/sadgrlonline/magnetic-poetry
"""

import json
import random
import re
from pathlib import Path

COMMON = [
    "a",
    "an",
    "the",
    "there",
    "is",
    "these",
    "those",
    "are",
    "they",
    "their",
    "she",
    "her",
    "he",
    "his",
    "me",
    "let",
    "I",
    "for",
    "am",
    "you",
    "because",
    "if",
    "be",
    "to",
    "too",
    "of",
    "in",
    "have",
    "first",
    "not",
    "on",
    "as",
    "at",
    "but",
    "by",
    "do",
    "from",
    "or",
    "will",
    "so",
    "get",
    "give",
    "would",
    "could",
    "should",
    "was",
    "go",
    "might",
    "were",
    "your",
    "us",
    "we",
    "them",
    "like",
    "let's",
    "and",
    "oh",
    "myself",
    "yourself",
    "anything",
    "nothing",
    "everything",
    "who",
    "what",
    "when",
    "come",
    "came",
    "where",
    "why",
    "won't",
    "see",
    "my",
    "more",
    "no",
    "want",
]

NOUNS = [
    "tree",
    "leaf",
    "star",
    "rose",
    "thing",
    "mushroom",
    "toadstool",
    "willow",
    "canopy",
    "witch",
    "goddess",
    "mother",
    "stillness",
    "mistress",
    "stream",
    "meadow",
    "deer",
    "pond",
    "gate",
    "crystal",
    "river",
    "cave",
    "mystery",
    "cliff",
    "forest",
    "woods",
    "chains",
    "bat",
    "owl",
    "butterfly",
    "moth",
    "serpent",
    "mermaid",
    "frog",
    "toad",
    "creature",
    "wolf",
    "cat",
    "bird",
    "fog",
    "wing",
    "insect",
    "critter",
    "poison",
    "rainwater",
    "storm",
    "weapon",
    "hunger",
    "acid",
    "wood",
    "passion",
    "moon",
    "garden",
    "vine",
    "iris",
    "azalea",
    "pine",
    "petal",
    "dawn",
    "vision",
    "sky",
    "throat",
    "cloud",
    "bough",
    "lilac",
    "silver",
    "cream",
    "strength",
    "desert",
    "light",
    "shadow",
    "dew",
    "myth",
    "sea-foam",
    "honey",
    "nectar",
    "face",
    "gloam",
    "body",
    "weakness",
    "pollen",
    "snow",
    "savage",
    "sand",
    "mist",
    "tea",
    "bark",
    "rebirth",
    "death",
    "eternity",
    "mercy",
    "mouth",
    "blood",
    "sword",
    "spirit",
    "burial",
    "destruction",
    "elixir",
    "teeth",
    "scent",
    "morning",
    "evening",
    "night",
    "tide",
    "seawater",
    "coffee",
    "neck",
    "glass",
    "pearl",
    "monster",
    "flower",
    "earth",
    "woman",
    "shield",
    "pattern",
    "hole",
    "dessert",
    "salt",
    "hope",
    "temple",
    "space",
    "serendipity",
    "bubble",
    "twilight",
    "growth",
    "hand",
    "war",
    "limit",
    "outside",
    "violence",
    "sorrow",
    "stem",
    "cowardice",
    "sandbar",
    "dusk",
    "eyes",
    "life",
    "mind",
    "blossom",
    "labor",
    "voice",
    "honeydew",
    "unknown",
    "sunbeam",
    "home",
    "moment",
    "warrior",
    "day",
    "gum",
    "midday",
    "catharsis",
    "tongue",
    "haze",
    "birth",
    "afternoon",
    "pain",
    "wilderness",
    "lagoon",
    "planet",
    "arch",
]

VERBS = [
    "hang",
    "say",
    "tell",
    "ask",
    "caught",
    "find",
    "shine",
    "listen",
    "glitter",
    "nestle",
    "flicker",
    "glow",
    "form",
    "cloak",
    "walk",
    "fade",
    "sparkle",
    "cling",
    "shape",
    "dig",
    "hover",
    "remind",
    "pulse",
    "break",
    "crawl",
    "smile",
    "hold",
    "create",
    "drift",
    "crack",
    "stay",
    "drip",
    "flash",
    "sweep",
    "know",
    "writhe",
    "bloom",
    "brim",
    "awake",
    "asleep",
    "grow",
    "bask",
    "fold",
    "split",
    "splinter",
    "ignite",
    "illuminate",
    "intensify",
    "gravitate",
    "clutch",
    "cower",
    "lie",
    "swallow",
    "soar",
    "shrivel",
    "shimmer",
    "crunch",
    "float",
    "breathe",
    "weave",
    "make",
    "crush",
    "bounce",
    "veil",
    "soak",
    "shrink",
    "warp",
    "reflect",
    "reach",
    "tremble",
    "whisper",
    "haunt",
    "bend",
    "pulsate",
    "push",
    "obliterate",
    "smooth",
    "roam",
    "love",
    "dive",
    "crash",
    "settle",
    "stretch",
    "blink",
    "awaken",
    "rush",
    "curl",
    "pull",
    "glide",
    "embrace",
    "lurch",
    "electrify",
    "roar",
    "squeeze",
    "grasp",
    "fragment",
    "catapult",
    "surrender",
    "march",
    "howl",
    "decay",
    "growl",
    "groan",
    "smell",
    "look",
    "forgive",
    "scream",
    "weep",
    "devastate",
    "shatter",
    "watch",
    "dance",
    "touch",
    "show",
    "believe",
]

ADJECTIVES = [
    "cool",
    "pale",
    "sharp",
    "sacred",
    "beautiful",
    "dark",
    "infinite",
    "unhurried",
    "flat",
    "strange",
    "outer",
    "fair",
    "fresh",
    "quiet",
    "dear",
    "empty",
    "magical",
    "pretty",
    "deep",
    "dying",
    "uninterrupted",
    "round",
    "crimson",
    "young",
    "other",
    "alive",
    "patient",
    "starless",
    "cheap",
    "feral",
    "brittle",
    "tight",
    "half-lit",
    "cascading",
    "full",
    "bright",
    "fringed",
    "forbidden",
    "tangled",
    "sunless",
    "twisted",
    "unsteady",
    "mystical",
    "silken",
    "soft",
    "still",
    "sweet",
    "warm",
    "short",
    "open",
    "unsettled",
    "sleepy",
    "powerful",
    "perfumed",
    "wet",
    "burnt",
    "long",
    "snowy",
    "thick",
    "stagnant",
    "purple",
    "black",
    "green",
    "pink",
    "yellow",
    "blue",
    "red",
    "orange",
    "violet",
    "loose",
    "broken",
    "milky",
    "unyielding",
    "bleak",
    "bewitched",
    "bruised",
    "cloudy",
    "cruel",
    "deadly",
    "dry",
    "electric",
    "fearless",
    "frozen",
    "funny",
    "glistening",
    "glossy",
    "growing",
    "hasty",
    "hollow",
    "hoarse",
    "hot",
    "hungry",
    "idle",
    "knowing",
    "leafy",
    "lost",
    "low",
    "melodic",
    "mild",
    "misty",
    "modest",
    "muddy",
    "mysterious",
    "necessary",
    "new",
    "normal",
    "obvious",
    "old",
    "plump",
    "proud",
    "pure",
    "raw",
    "rich",
    "ripe",
    "sandy",
    "scarce",
    "shimmering",
    "slight",
    "small",
    "steel",
    "tender",
    "thorny",
    "tired",
    "twin",
    "useful",
    "vacant",
    "vivid",
    "warlike",
    "weak",
    "weird",
    "wild",
    "wooden",
]

ADVERBS = [
    "warmly",
    "barely",
    "sleepily",
    "sadly",
    "slowly",
    "here",
    "clumsily",
    "curiously",
    "wistfully",
    "farthest",
    "endlessly",
    "darkest",
    "boldly",
    "brightly",
    "terribly",
    "always",
    "sickly",
    "often",
    "tomorrow",
    "quickly",
    "safely",
    "quietly",
    "wildly",
    "hard",
    "fast",
    "bravely",
    "however",
    "nonetheless",
    "clearly",
    "easily",
    "fiercely",
    "foolishly",
    "heavily",
    "wisely",
    "wearily",
    "unwillingly",
    "ultimately",
    "suddenly",
    "shakily",
    "seemingly",
    "rarely",
    "obediently",
    "naturally",
    "increasingly",
    "noiselessly",
    "deafeningly",
    "weakly",
    "cruelly",
]

PREPOSITIONS = [
    "above",
    "about",
    "around",
    "between",
    "despite",
    "except",
    "without",
    "beside",
    "among",
    "beneath",
    "across",
    "before",
    "behind",
    "below",
    "onto",
    "inside",
    "under",
    "up",
    "with",
    "over",
    "away",
    "along",
    "next",
    "underneath",
    "until",
    "within",
    "toward",
]

# Bounds per category: (pool, min, max). Total of mins <= NUM_WORDS <= total of maxes.
BOUNDS = {
    "common": (COMMON, 3, 6),
    "nouns": (NOUNS, 4, 8),
    "verbs": (VERBS, 3, 6),
    "adjectives": (ADJECTIVES, 2, 5),
    "adverbs": (ADVERBS, 1, 3),
    "prepositions": (PREPOSITIONS, 1, 3),
}

NUM_WORDS = 25
CANVAS_WIDTH = 504
CANVAS_HEIGHT = 600

INDEX_PATH = Path(__file__).parent / "public" / "index.html"


def pick_counts() -> dict[str, int]:
    """Pick a count for each category within bounds, totalling NUM_WORDS."""
    counts = {name: lo for name, (_, lo, _) in BOUNDS.items()}
    remaining = NUM_WORDS - sum(counts.values())

    while remaining > 0:
        candidates = [name for name, (_, _, hi) in BOUNDS.items() if counts[name] < hi]
        if not candidates:
            break
        choice = random.choice(candidates)
        counts[choice] += 1
        remaining -= 1

    return counts


def pick_words() -> list[dict]:
    counts = pick_counts()
    chosen = []
    for name, n in counts.items():
        pool = BOUNDS[name][0]
        chosen.extend(random.sample(pool, n))
    random.shuffle(chosen)

    return [
        {
            "text": word,
            "x": random.randint(20, CANVAS_WIDTH - 80),
            "y": random.randint(20, CANVAS_HEIGHT - 30),
            "rotation": round(random.uniform(-3, 3), 1),
        }
        for word in chosen
    ]


def format_words(words: list[dict]) -> str:
    lines = []
    for w in words:
        lines.append(
            f"      {{text: {json.dumps(w['text'])}, x: {w['x']}, y: {w['y']}, rotation: {w['rotation']}}},"
        )
    return "const INITIAL_WORDS = [\n" + "\n".join(lines) + "\n    ];"


def main() -> None:
    words = pick_words()
    new_block = format_words(words)

    html = INDEX_PATH.read_text()
    updated = re.sub(
        r"const INITIAL_WORDS = \[.*?\];",
        new_block,
        html,
        count=1,
        flags=re.DOTALL,
    )

    INDEX_PATH.write_text(updated)
    print(f"Picked {NUM_WORDS} words: {', '.join(w['text'] for w in words)}")


if __name__ == "__main__":
    main()
